Nt = 10000
Nx = 401
Ny = 201
Xmin = 0.0
Xmax = 2.0
Ymin = 0.0
Ymax = 1.0

cfl = 0.25
D1 = "JP6"
D2 = "JP6"

# idtype options:  waveguide, gaussian
id_type = "waveguide"

id_B0 = 1.0

#waveguide params
id_mode_m = 5
id_mode_n = 3

#gaussian params
id_x0 = 0.0
id_y0 = 0.0
id_sigma = 0.5


output_dir = "output_maxwell"
output_interval = 50
