Nt = 10000
Nx = 10001
Xmin = -100.0
Xmax = 100.0

NGhost = 3
cfl = 0.1
eta = 2.0
D1 = "KP4"
D2 = "JP6"

Filter = "KO8"
KOsigma = 0.5
ApplyDissBounds = true

# initial data types = [ "Puncture", "EddingtonFinkelstein" ]
Mass = 1.0
collapsed_lapse = true
initial_data = "Puncture"

# output parameters
output_dir = "output_bssn"
output_interval = 20
print_interval = 5
