Nt = 3200
Nx = 101
Ny = 101
Xmin = -5.0
Xmax = 5.0
Ymin = -5.0
Ymax = 5.0

cfl = 0.1
D1 = "JP6"
D2 = "JP6"

id_x0 = 0.0
id_y0 = 0.0
id_sigma = 1.0
id_amp = 1.0
bound_cond = "SOMMERFELD"

output_dir = "output_sowave"
output_interval = 5
